### ISSUE TITLE
Porting to C++ and merging into INET/OMNeT++

### ISSUE THREAD

**Issue by levy** [ACassimiro/TSNsched#11]
Hi!

My name is Levente Mészáros and I'm one of the core developers of the [INET Framework](https://github.com/inet-framework/inet) for the [OMNeT++](https://omnetpp.org/) network simulator tool . Recently, INET has been extended with TSN features and I found your TSNsched project very interesting. I would like to port it to C++ and include it in the INET framework project. In the future, I'm planning to add stream redundancy support. Of course, I would give all credits to you in the source files. Do you mind this?

Best wishes,
levy

**Comment by ACassimiro** [comment]
Handled via e-mail.
