### ISSUE TITLE
Priorities of different Fragments

### ISSUE THREAD

**Issue by LQ-lq** [ACassimiro/TSNsched#7]
Hello,
Why do different fragments of a stream have different priorities?
What determines this priority?
Wasn't the priority of each stream initially defined by the user?
Another question is, Where is the maximum latency that can be tolerated per flow set? I now want to change the maximum latency of a flow, but I can't find the corresponding code.

**Comment by ACassimiro** [comment]
Hello, 

By default, TSNsched considers that the input network is 802.1Qci compliant. According to "S. S. Craciunas, R. S. Oliver, and T. C. AG.  An overview of scheduling mechanisms for time-sensitive networks. Proceedings of the Real-time summer school LÉcole dÉtéTemps Réel (ETR), 2017", the IEEE 802.1Qci standard also plays an important part in the scheduling approach used by TSNsched (if configured to be used), as it provides the necessary grounds to identification of streams and modification of packet headers performed on switches. Although it is not necessary, this functionality can improve the efficiency of TSNsched for generating schedules. This can be configured by using the flowObject.fixedPriority(true), where flowObject is the name of the variable of your flow before running the scheduleGenerator.generateSchedule(net) method.

Also, according to our research on methodologies of critical traffic scheduling for TSN, TSNsched allows the solver to define the priority of the traffic, so, for us, that's usually output. Still, you can set the priority yourself, if you need. After using the flowObject.fixedPriority(true) method, you can set your priority with the flowObject.setPriorityValue(int prt) method, using the integer equivalent for the priority that you'd like to use as a parameter. Note that both methods should be used before calling the scheduleGenerator.generateSchedule(net) method.

The maximum allowed latency is set on the starting device of the flow. See one of the constructor methods of the class device:

```
public Device(float packetPeriodicity,
                  float firstT1Time,
                  float hardConstraintTime,
                  float packetSize)
```

The third parameter, hardConstraintTime, is the maximum allowed latency tolerated by the device. You can configure the maximum latency by changing this variable on the creation of your device object.

Hope this helps. :)
